### PR TITLE
Wrap VarScan

### PR DESCRIPTION
**Pull request by ernfrid**
This is an attempt to fix TCGA validation errors by running VarScan through a wrapper. I also attempted to update the XML file. Please let me know if you run into any problems or notice any part of this that looks problematic or incorrect. I have tested on chr21 for a test BAM.

### CODE REVIEW

**Comment by jacmarjorie** [comment]
"FORMAT value 'GT:GQ:DP:RD:AD:FREQ:DP4' is not valid. The following mandatory format fields are missing: BQ,SS"

has now changed to a report that:

"FORMAT value 'GT:GQ:DP:RD:AD:FREQ:DP4:BQ:SS' is not valid. Format data contains a field that has not been defined in the headers: 'BQ'" as well as "VCF data validation error on line 23: INFO value 'SS' is not valid. ID not defined in headers".

There could potentially be more, but the program haults after alternating back and forth between these two errors for 120 lines in the vcf. This is happening for both the indel and the snp file.

**Comment by ernfrid** [comment]
I think I have fixes for this and I also made an attempt at updating the VarScan version to be used.

Please note that even if this is all correct, VarScan should still be run through the fpfilter tool I put together for SomaticSniper as well.

**Comment by jacmarjorie** [comment]
Thanks @ernfrid. I have been testing using the fpfilter.

I will post the results of your varscan wrapper updates later today.

**Comment by jacmarjorie** [comment]
Two open issues before this PR can be accepted:
1. indel.vcf throws this error during validation:

VCF data validation error on line 282: FILTER value 'str10' is not valid. The value of the Filter must be PASS or correspond to an ID in the FILTER headers
1. snp.vcf produced from this version of varscan has 0 lines (ignoring header), currently inspecting intermediate files... @ernfrid is this error duplicated on your end, by chance?

**Comment by ernfrid** [comment]
Let me see. We may want to roll back to 2.3.9.

**Comment by ernfrid** [comment]
Ok. I'm going to roll back the Dockerfile and the xml changes. Let's make sure the wrapper works first?

**Comment by jacmarjorie** [comment]
As of now, the wrapper will just need to address the FILTER error I reported above. If you want to roll back the docker changes, I can re-test the validation and let you know if the FILTER error persists. 

Also, for future reference: I just ran the varscan-2.3.10 docker inside, looks like there is content in the intermediate snp file, but again not in the final output (pre-fpfilter). Seems like snps are being lost in some filtering step.

**Comment by ernfrid** [comment]
Ok. Dan has confirmed that the filter has existed for a while. I will add a line in the wrapper and have reported the bug.

**Comment by ernfrid** [comment]
My internal test is working fine with 2.4.0 in terms of the SNP file. I'm launching a larger test and I'll see if I can replicate.

**Comment by jacmarjorie** [comment]
Out of curiosity, are you running tests via the docker? 

I'm using mpileups of testexome.pair0 from here: http://hgwdev.sdsc.edu/~hannes/testexomes/, which produced a nonempty snp file when ran on 2.3.9, but not on 2.4.0.

**Comment by jacmarjorie** [comment]
Not sure the issue before, but I now successfully have snp output from 2.4.0. Stay tuned for compliance.

**Comment by ernfrid** [comment]
Excellent! To answer your earlier question, no — I have not been running in Docker. Our internal image is too old to support that and I have not set up a VM.

**Comment by jacmarjorie** [comment]
Congrats! All TCGA compliance errors have been filtered through on your end. @kellrott please merge this PR.

**Comment by ernfrid** [comment]
Hurray! Please let me know if anything else crops up.

**Pull request merged**
